---
name: "Build & Push Docker Image"

env:
  DOCKERHUB_USERNAME: martinbouillaud
  DOCKERHUB_IMAGE: docker-openvpn

on:
  schedule:
    - cron:  '0 2 1,7,14,31 * *'
  push:
    branches:
      - 'master'

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{env.DOCKERHUB_USERNAME}}/${{env.DOCKERHUB_IMAGE}}
          tags: type=ref,event=tag

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{env.DOCKERHUB_USERNAME}}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v8
          push: true
          tags: ${{env.DOCKERHUB_USERNAME}}/${{env.DOCKERHUB_IMAGE}}:latest
